blog/urls.py
from django.urls import path

from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list_view, name="post_list"),
    path("<slug:post_slug>", views.post_details_view, name="post_details"),
    path(
        "category/<slug:category_slug>/",
        views.post_list_view,
        name="category_post_list",
    ),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = "cart"

urlpatterns = [
    path("<uuid:cart_uuid>/", views.cart_details, name="cart_details"),
    path("add/item/", views.add_item, name="add_item"),
    path("pay/", views.pay, name="pay"),
    path("", views.carts_list, name="carts_list"),
]

daneshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from daneshop import api

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("blog/", include("blog.urls")),
        path("cart/", include("cart.urls")),
        path("", include("shop.urls")),
        path("v1/api/", include(api)),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"

urlpatterns = [
    path("", views.shop_product_list_view, name="home"),
    path(
        "<slug:product_slug>",
        views.shop_product_details_view,
        name="product_details",
    ),
    path("categories/", views.shop_category_list_view, name="categories"),
    path(
        "category/<slug:category_slug>",
        views.shop_product_list_view,
        name="category_products",
    ),
]

cart/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from daneshop.models import BaseModel
from shop.models import Product


class Cart(BaseModel):
    class CartStatus(models.TextChoices):
        PAID = "paid", _("PAID")
        NOT_PAID = "not_paid", _("NO_TPAID")

    cart_status = models.CharField(
        max_length=25,
        choices=CartStatus.choices,
        default=CartStatus.NOT_PAID,
        help_text=_("Status"),
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="carts",
    )
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self):
        return f"Cart for {self.user.username}"

    def is_defined(self, product: Product):
        item = CartItem.objects.filter(cart=self, product=product)
        if item.exists():
            return True
        else:
            return False

    def get_absolute_url(self):
        return reverse("cart:cart_details", kwargs={"cart_uuid": self.uuid})


class CartItem(BaseModel):
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        related_name="items",
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.product.title} ({self.quantity}) in Cart"

    def total_price(self):
        return self.product.last_price.price * self.quantity

cart/forms.py
from django import forms


class CartItemForm(forms.Form):
    product_slug = forms.SlugField()
    quantity = forms.IntegerField()

cart/views.py
from django.shortcuts import HttpResponse, redirect, render

from cart import services
from cart.forms import CartItemForm


def cart_details(request, cart_uuid: str):
    cart = services.get_cart_details(cart_uuid)
    items = services.get_cart_items(cart_uuid)
    context = {"cart": cart, "items": items}
    return render(request, "cart/pages/cart.html", context)


def add_item(request):
    if request.method == "POST":
        form = CartItemForm(request.POST)
        if form.is_valid():
            product_slug = form.cleaned_data["product_slug"]
            quantity = form.cleaned_data["quantity"]
            services.add_item(request, product_slug, quantity)
            return HttpResponse("success")
    return HttpResponse("fail")


def pay(request):
    if request.method == "POST":
        services.pay(request)
    return redirect("shop:home")


def carts_list(request):
    carts = services.get_carts_list(request)
    context = {"carts": carts}
    return render(request, "cart/pages/carts.html", context)

cart/templates/cart/pages/cart.html
{% extends 'shop/base.html' %}
{% load cart_tags %}

{% block title %}
    Cart {{ cart.uuid }}
{% endblock title %}


{% block content %}
<div class="container">
    <main>

      <div class="row g-5">
        <div class="col-md col-lg order-md-last">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-primary">Your cart</span>
            <span class="badge bg-primary rounded-pill">
              {% cart_items_count cart.uuid%}
            </span>
          </h4>
          <ul class="list-group mb-3">

            {% for item in items %}

              <li class="list-group-item d-flex justify-content-between lh-sm">
                <div>
                  <h6 class="my-0">{{ item.product.title|title }}</h6>
                  <small class="text-body-secondary">{{ item.product.description|truncatechars:40 }}</small>
                  <small>
                    <a href="{% url 'shop:product_details' item.product.slug %}">more</a>
                  </small>
                </div>
                <span></span>
                <span class="text-body-secondary">
                  ({{ item.quantity }}) &#xd7 ${{ item.product.last_price.price }} = <strong>{{ item.total_price }}</strong>
                </span>
              </li>

            {% endfor %}

            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>${% cart_total_price cart.uuid %}</strong>
            </li>

          </ul>
        </div>
         </div>
    </main>
    <div class="container mb-3">
      <div class="row justify-content-end">
        <div class="col-auto">
          <form action="{% url 'cart:pay' %}" method="POST">
              {% csrf_token %}
              <button class="btn btn-success" type="submit">
                Pay
              </button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

cart/templates/cart/pages/carts.html
{% extends 'shop/base.html' %}


{% block title %}
    Carts
{% endblock title %}



{% block content %}
<div class="container">
    <h3>Cards</h3>
    <div class="row">

        {% for cart in carts %}
            <div class="col-12 mb-3">
                <div class="card">
                    <div class="card-body">
                    <div class="row justify-content-between">
                        <div class="col-auto">
                            <h5 class="card-title">Cart unique id: {{ cart.uuid }}</h5>
                        </div>
                        <div class="col-auto">
                            <span><small>
                                Status: <span class="text-success">{{cart.cart_status}}</span>
                            </small></span>
                        </div>
                    </div>
                    <p class="card-text">Pay at {{ cart.updated_at }}

                    </p>
                    <a href="{% url 'cart:cart_details' cart.uuid %}" class="btn btn-primary">Read more</a>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
</div>
{% endblock content %}