blog/urls.py
from django.urls import path

from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list_view, name="post_list"),
    path("<slug:post_slug>", views.post_details_view, name="post_details"),
    path(
        "category/<slug:category_slug>/",
        views.post_list_view,
        name="category_post_list",
    ),
]

daneshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from daneshop import api

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("blog/", include("blog.urls")),
        path("cart/", include("cart.urls")),
        path("", include("shop.urls")),
        path("v1/api/", include(api)),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"

urlpatterns = [
    path("", views.shop_product_list_view, name="home"),
    path(
        "<slug:product_slug>",
        views.shop_product_details_view,
        name="product_details",
    ),
    path("categories/", views.shop_category_list_view, name="categories"),
    path(
        "category/<slug:category_slug>",
        views.shop_product_list_view,
        name="category_products",
    ),
]

shop/models/category.py
from django.db import models
from django.utils.text import slugify

from daneshop.models import BaseModel


class ProductCategory(BaseModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        related_name="child",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

shop/models/media.py
import os
import uuid

from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from daneshop.models import BaseModel


def author_title_upload_path(instance, filename):
    ext = filename.split(".")[-1]
    product = instance.product
    slug = slugify(product.title)
    path = f"product_{product.id}/{slug}"
    unique_filename = f"{uuid.uuid4()}.{ext}"
    return os.path.join(path, unique_filename)


class ProductMedia(BaseModel):
    class FileType(models.TextChoices):
        IMAGE = "image", _("IMAGE")
        VIDEO = "video", _("VIDEO")

    file_type = models.CharField(
        max_length=25,
        choices=FileType.choices,
        default=FileType.IMAGE,
        help_text=_("File Type"),
    )

    file = models.FileField(
        upload_to=author_title_upload_path,
        null=True,
        blank=True,
    )
    product = models.ForeignKey(
        "Product",
        on_delete=models.CASCADE,
        related_name="medias",
    )

    def __str__(self):
        return f"{self.file_type}: {self.product.title}"

shop/models/price.py
from django.db import models

from daneshop.models import BaseModel


class ProductPrice(BaseModel):
    product = models.ForeignKey(
        "Product", related_name="prices", on_delete=models.CASCADE
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    effective_date = models.DateField()

    class Meta:
        verbose_name = "Product Price"
        verbose_name_plural = "Product Prices"
        ordering = ("effective_date",)

    def __str__(self):
        return f"{self.product.title} - {self.price} - {self.effective_date}"

shop/models/product.py
from django.db import models
from django.db.models import JSONField
from django.urls import reverse

from daneshop.models import BaseModel

from .category import ProductCategory
from .media import ProductMedia
from .price import ProductPrice


class Product(BaseModel):
    category = models.ForeignKey(
        ProductCategory, related_name="products", on_delete=models.CASCADE
    )

    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    attributes = JSONField(blank=True, null=True)

    @property
    def last_price(self):
        return ProductPrice.objects.all().filter(product=self).last()

    @property
    def get_media(self):
        return (
            ProductMedia.objects.all()
            .filter(
                product=self,
                file_type="image",
            )
            .first()
        )

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"
        ordering = ("created_at",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "shop:product_details",
            kwargs={"product_slug": self.slug},
        )

shop/views.py
from django.shortcuts import render

from shop import services


def shop_product_list_view(request, category_slug: str = ""):
    page_number = request.GET.get("page", 1)
    products = services.get_products_list(category_slug, page_number)
    context = {"products": products}
    return render(request, "shop/pages/main.html", context)


def shop_product_details_view(request, product_slug: str):
    product = services.get_product_details(product_slug=product_slug)
    context = {"product": product}
    return render(request, "shop/pages/product.html", context)


def shop_category_list_view(request):
    categories = services.get_categories_list()
    context = {"categories": categories}
    return render(request, "shop/pages/categories.html", context)

shop/templates/shop/pages/categories.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    Category List | DaneShop
{% endblock title %}


{% block content %}
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Toys, Category </h1>
                    <p class="lead fw-normal text-white-50 mb-0"></p>
                </div>
            </div>
        </header>
        <!-- Section-->

        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4">
                    <div class="list-group">
                        {% for cat in categories %}
                            <a href="{% url 'shop:category_products' cat.slug %}" class="list-group-item list-group-item-action list-group-item-action">{{ cat.name|title }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>

{% endblock content %}

shop/templates/shop/pages/main.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    DaneShop - Your Last TOYs!
{% endblock title %}


{% block content %}
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Toys, in your dream as </h1>
                    <p class="lead fw-normal text-white-50 mb-0"></p>
                </div>
            </div>
        </header>
        <!-- Section-->

        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4">
                    {% for toy in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->

                            {% if toy.get_media %}
                                <img class="card-img-top"
                                src="{{ toy.get_media.file.url }}" alt="..."
                                width="268" height="178" style="object-fit: cover;"
                                />
                            {% else %}
                                <img class="card-img-top"
                                src="https://cdn.firstcry.com/education/2022/11/06094158/Toy-Names-For-Kids.jpg" alt="..."
                                width="268" height="178" style="object-fit: cover;"
                                />
                            {% endif %}
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ toy.title|title }}</h5>
                                    <!-- Product price-->
                                    ${{ toy.last_price.price }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ toy.get_absolute_url }}">View toy</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
                <div class="row justify-content-center">
                    <div class="col-auto">
                        {% include 'shop/component/pagination.html' %}
                    </div>
                </div>
            </div>
        </section>

{% endblock content %}

shop/templates/shop/pages/product.html
{% extends 'shop/base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    {{ product.title|title}} | DaneShop
{% endblock title %}



{% block content %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-8" id="alert">

                </div>
            </div>
        </div>
        <!-- Product section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">

                    {% if product.get_media %}
                        <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0"
                            style="object-fit: cover;"
                            src="{{ product.get_media.file.url }}" alt="..." /></div>
                    {% else %}
                        <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0"
                            style="object-fit: cover;"
                            src="https://cdn.firstcry.com/education/2022/11/06094158/Toy-Names-For-Kids.jpg" alt="..." /></div>
                    {% endif %}

                    <div class="col-md-6">
                        <div class="small mb-1">category: {{ product.category }}</div>
                        <h1 class="display-5 fw-bolder">{{ product.title|title}}</h1>
                        <div class="fs-5 mb-5">
                            <span>${{ product.last_price.price}}</span>
                        </div>
                        <p class="lead">{{ product.description|truncatewords:50 }}</p>
                        <form action="" method="POST">
                            <div class="d-flex">
                                {% csrf_token %}
                                <input class="form-control text-center me-3" id="quantity" type="num" value="1" style="max-width: 3rem" />
                                <input id="product_slug" type="hidden" value="{{ product.slug }}"/>

                                <button id="addToCart" class="btn btn-outline-dark flex-shrink-0" type="">
                                    <i class="bi-cart-fill me-1"></i>
                                    Add to cart
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- Product Details -->
        <section class="py-5 bg-light">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row justify-content-center">
                    <div class="col-md-10">
                        <div class="table-responsive">
                            <table class="table text-start">
                            <tbody>

                                {% for attr, val in product.attributes.items %}
                                    <tr>
                                        <th scope="row" class="text-start">{{attr}}</th>
                                        <td>
                                            {{ val }}
                                        </td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Related items section-->
        <section class="py-5 bg-light">
            <div class="container px-4 px-lg-5 mt-5">
                <h2 class="fw-bolder mb-4">Related products</h2>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% related_products product.slug product.category.slug %}
                </div>
            </div>
        </section>
{% endblock content %}