blog/urls.py
from django.urls import path

from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list_view, name="post_list"),
    path("<slug:post_slug>", views.post_details_view, name="post_details"),
    path(
        "category/<slug:category_slug>/",
        views.post_list_view,
        name="category_post_list",
    ),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = "cart"

urlpatterns = [
    path("<uuid:cart_uuid>/", views.cart_details, name="cart_details"),
    path("add/item/", views.add_item, name="add_item"),
    path("pay/", views.pay, name="pay"),
    path("", views.carts_list, name="carts_list"),
]

daneshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from daneshop import api

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("blog/", include("blog.urls")),
        path("cart/", include("cart.urls")),
        path("", include("shop.urls")),
        path("v1/api/", include(api)),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"

urlpatterns = [
    path("", views.shop_product_list_view, name="home"),
    path(
        "<slug:product_slug>",
        views.shop_product_details_view,
        name="product_details",
    ),
    path("categories/", views.shop_category_list_view, name="categories"),
    path(
        "category/<slug:category_slug>",
        views.shop_product_list_view,
        name="category_products",
    ),
]

shop/models/category.py
from django.db import models
from django.utils.text import slugify

from daneshop.models import BaseModel


class ProductCategory(BaseModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        related_name="child",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

shop/models/media.py
import os
import uuid

from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from daneshop.models import BaseModel


def author_title_upload_path(instance, filename):
    ext = filename.split(".")[-1]
    product = instance.product
    slug = slugify(product.title)
    path = f"product_{product.id}/{slug}"
    unique_filename = f"{uuid.uuid4()}.{ext}"
    return os.path.join(path, unique_filename)


class ProductMedia(BaseModel):
    class FileType(models.TextChoices):
        IMAGE = "image", _("IMAGE")
        VIDEO = "video", _("VIDEO")

    file_type = models.CharField(
        max_length=25,
        choices=FileType.choices,
        default=FileType.IMAGE,
        help_text=_("File Type"),
    )

    file = models.FileField(
        upload_to=author_title_upload_path,
        null=True,
        blank=True,
    )
    product = models.ForeignKey(
        "Product",
        on_delete=models.CASCADE,
        related_name="medias",
    )

    def __str__(self):
        return f"{self.file_type}: {self.product.title}"

shop/models/price.py
from django.db import models

from daneshop.models import BaseModel


class ProductPrice(BaseModel):
    product = models.ForeignKey(
        "Product", related_name="prices", on_delete=models.CASCADE
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    effective_date = models.DateField()

    class Meta:
        verbose_name = "Product Price"
        verbose_name_plural = "Product Prices"
        ordering = ("effective_date",)

    def __str__(self):
        return f"{self.product.title} - {self.price} - {self.effective_date}"

shop/models/product.py
from django.db import models
from django.db.models import JSONField
from django.urls import reverse

from daneshop.models import BaseModel

from .category import ProductCategory
from .media import ProductMedia
from .price import ProductPrice


class Product(BaseModel):
    category = models.ForeignKey(
        ProductCategory, related_name="products", on_delete=models.CASCADE
    )

    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    attributes = JSONField(blank=True, null=True)

    @property
    def last_price(self):
        return ProductPrice.objects.all().filter(product=self).last()

    @property
    def get_media(self):
        return (
            ProductMedia.objects.all()
            .filter(
                product=self,
                file_type="image",
            )
            .first()
        )

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"
        ordering = ("created_at",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "shop:product_details",
            kwargs={"product_slug": self.slug},
        )

shop/views.py
from django.shortcuts import render

from shop import services


def shop_product_list_view(request, category_slug: str = ""):
    page_number = request.GET.get("page", 1)
    products = services.get_products_list(category_slug, page_number)
    context = {"products": products}
    return render(request, "shop/pages/main.html", context)


def shop_product_details_view(request, product_slug: str):
    product = services.get_product_details(product_slug=product_slug)
    context = {"product": product}
    return render(request, "shop/pages/product.html", context)


def shop_category_list_view(request):
    categories = services.get_categories_list()
    context = {"categories": categories}
    return render(request, "shop/pages/categories.html", context)

shop/templates/shop/base.html
{% load static %}
{% load cart_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>

            {% block blockname %}

            {% endblock blockname %}

        </title>
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'shop:home' %}">DaneShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                            href="{% url 'shop:categories' %}">Categorisses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                            href="{% url 'cart:carts_list' %}">Carts</a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a></li>
                    </ul>

                        {% has_cart user.username as res %}
                        {% cart_items_count res as count %}

                            {% if res %}
                                <a class="btn btn-outline-dark" href="{% url 'cart:cart_details' res %}">
                                    <i class="bi-cart-fill me-1"></i>
                                    Cart
                                    <span class="badge bg-dark text-white ms-1 rounded-pill">
                                        {{count}}
                                    </span>
                                </a>
                            {% else %}
                                <a class="btn btn-outline-dark" href="{% url 'cart:cart_details' res %}">
                                    <i class="bi-cart-fill me-1"></i>
                                    Cart
                                    <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                                </a>
                            {% endif %}


                </div>
            </div>
        </nav>

        {% block content %}

        {% endblock content %}

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
        <script src="{% static 'shop/js/jquery.js' %}"></script>
        <script src="{% static 'shop/js/script.js' %}"></script>
    </body>
</html>